/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.coursework;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Sulav
 */
public class AppliancesInfo extends javax.swing.JFrame {
    private ArrayList<EverestComputers> Item = new ArrayList();
    /**
     * Creates new form Coursework
     */
    public AppliancesInfo() {
        initComponents();
        setIcon();
        showDate();
        showTime();
    }
    
    private void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM/dd/yyyy");
        lblDate.setText("Date: " + s.format(d)); //Displays current date in lblDate
    }

    private void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("HH:mm a");
                lblTime.setText("Time: " + s.format(d)); ////Displays current time in lblTime
            }
        }).start();
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("everest_1.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpRecommendation = new javax.swing.ButtonGroup();
        dboxAbout = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        lblLogoAbout = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAbout = new javax.swing.JTextArea();
        jTabbedPaneAddSearch = new javax.swing.JTabbedPane();
        jPanelAdd = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();
        lblModelNumber = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblRange = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        rbtnLow = new javax.swing.JRadioButton();
        txtModelNumber = new javax.swing.JTextField();
        rbtnMedium = new javax.swing.JRadioButton();
        rbtnHigh = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cbDiscount = new javax.swing.JComboBox<>();
        jPanelSearch = new javax.swing.JPanel();
        jPanelSearchByItem = new javax.swing.JPanel();
        cbSearchByCategory = new javax.swing.JComboBox<>();
        btnSearchByCategory = new javax.swing.JButton();
        jPanelSearchByPrice = new javax.swing.JPanel();
        txtSearchByPrice = new javax.swing.JTextField();
        btnSearchByPrice = new javax.swing.JButton();
        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        lblEverestComputers = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miOpen = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        miImport = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        miFAQs = new javax.swing.JMenuItem();
        mAbout = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        dboxAbout.setTitle("About");
        dboxAbout.setName("About"); // NOI18N
        dboxAbout.setUndecorated(true);
        dboxAbout.setResizable(false);
        dboxAbout.setSize(new java.awt.Dimension(410, 540));
        dboxAbout.getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(252, 252, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

        lblLogoAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/everest_1.png"))); // NOI18N

        btnOk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitle.setText("Everest Computers Pvt. Ltd.");

        txtAbout.setEditable(false);
        txtAbout.setColumns(20);
        txtAbout.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAbout.setLineWrap(true);
        txtAbout.setRows(5);
        txtAbout.setTabSize(10);
        txtAbout.setText(" Everest Computers Pvt. Ltd is an enterprise that offers the best price on computer products, laptop computer and electronic appliances.\n\n This application system is developed for managing       data of electronic appliances stock available in the        enterprise such as model number, name of item,           category, recommendation, price and discount.\n\n This application makes the user easily search and         navigate to various appliances item by selecting the     specific category or price of an appliance.");
        txtAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(txtAbout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblLogoAbout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        dboxAbout.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 540);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Everest Computers Information System");
        setBackground(java.awt.SystemColor.window);
        setName("Everest Computers Information System"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPaneAddSearch.setBackground(new java.awt.Color(229, 229, 229));
        jTabbedPaneAddSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPaneAddSearch.setName(""); // NOI18N

        jPanelAdd.setBackground(java.awt.SystemColor.window);

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setText("Enter Name");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(153, 153, 153));
        txtPrice.setText("Enter Price");
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        cbCategory.setBackground(new java.awt.Color(102, 204, 255));
        cbCategory.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keyboard", "Mouse", "Monitor", "Speaker", "Graphics Card", "RAM", "SSD", "HDD" }));

        lblModelNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModelNumber.setText("Model Number:");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setText("Name:");

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory.setText("Category:");

        lblRange.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRange.setText("Range:");

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrice.setText("Price:");

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiscount.setText("Discount:");

        rbtnLow.setBackground(java.awt.SystemColor.window);
        btnGrpRecommendation.add(rbtnLow);
        rbtnLow.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbtnLow.setSelected(true);
        rbtnLow.setText("Low");

        txtModelNumber.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtModelNumber.setForeground(new java.awt.Color(153, 153, 153));
        txtModelNumber.setText("Enter Model Number");
        txtModelNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtModelNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModelNumberFocusLost(evt);
            }
        });

        rbtnMedium.setBackground(java.awt.SystemColor.window);
        btnGrpRecommendation.add(rbtnMedium);
        rbtnMedium.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbtnMedium.setText("Medium");

        rbtnHigh.setBackground(java.awt.SystemColor.window);
        btnGrpRecommendation.add(rbtnHigh);
        rbtnHigh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbtnHigh.setText("High");

        btnAdd.setBackground(new java.awt.Color(102, 204, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(70, 31));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(102, 204, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(61, 27));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cbDiscount.setBackground(new java.awt.Color(102, 204, 255));
        cbDiscount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "20%", "25%", "40%", "50%" }));

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(cbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddLayout.createSequentialGroup()
                                .addComponent(rbtnLow, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(rbtnHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addComponent(lblDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAddLayout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbDiscount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );

        jPanelAddLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbtnHigh, rbtnLow, rbtnMedium});

        jPanelAddLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCategory, lblDiscount, lblModelNumber, lblName, lblPrice, lblRange});

        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRange, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnLow)
                    .addComponent(rbtnMedium)
                    .addComponent(rbtnHigh))
                .addGap(13, 13, 13)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelAddLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbtnHigh, rbtnLow, rbtnMedium});

        jPanelAddLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCategory, lblDiscount, lblModelNumber, lblName, lblPrice, lblRange});

        jTabbedPaneAddSearch.addTab("Add Appliances    ", jPanelAdd);

        jPanelSearch.setBackground(java.awt.SystemColor.window);

        jPanelSearchByItem.setBackground(java.awt.SystemColor.window);
        jPanelSearchByItem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search by Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanelSearchByItem.setForeground(new java.awt.Color(255, 255, 255));

        cbSearchByCategory.setBackground(new java.awt.Color(102, 204, 255));
        cbSearchByCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbSearchByCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keyboard", "Mouse", "Monitor", "Speaker", "Graphics Card", "RAM", "SSD", "HDD" }));

        btnSearchByCategory.setBackground(new java.awt.Color(102, 204, 255));
        btnSearchByCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchByCategory.setText("Appliances available in category");
        btnSearchByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchByItemLayout = new javax.swing.GroupLayout(jPanelSearchByItem);
        jPanelSearchByItem.setLayout(jPanelSearchByItemLayout);
        jPanelSearchByItemLayout.setHorizontalGroup(
            jPanelSearchByItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchByItemLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanelSearchByItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchByCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSearchByCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelSearchByItemLayout.setVerticalGroup(
            jPanelSearchByItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchByItemLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cbSearchByCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchByCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelSearchByPrice.setBackground(java.awt.SystemColor.window);
        jPanelSearchByPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Search by Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtSearchByPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtSearchByPrice.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchByPrice.setText("Enter Price To Search");
        txtSearchByPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchByPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchByPriceFocusLost(evt);
            }
        });
        txtSearchByPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchByPriceKeyTyped(evt);
            }
        });

        btnSearchByPrice.setBackground(new java.awt.Color(102, 204, 255));
        btnSearchByPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchByPrice.setText("Search Appliance");
        btnSearchByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchByPriceLayout = new javax.swing.GroupLayout(jPanelSearchByPrice);
        jPanelSearchByPrice.setLayout(jPanelSearchByPriceLayout);
        jPanelSearchByPriceLayout.setHorizontalGroup(
            jPanelSearchByPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchByPriceLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelSearchByPriceLayout.setVerticalGroup(
            jPanelSearchByPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchByPriceLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelSearchByPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSearchByItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelSearchByItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanelSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPaneAddSearch.addTab("Search               ", jPanelSearch);

        getContentPane().add(jTabbedPaneAddSearch);
        jTabbedPaneAddSearch.setBounds(10, 147, 418, 405);

        jPanelTable.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appliances Information System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Model Number", "Name", "Category", "Recommendation", "Price", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfo.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblInfo);
        if (tblInfo.getColumnModel().getColumnCount() > 0) {
            tblInfo.getColumnModel().getColumn(0).setResizable(false);
            tblInfo.getColumnModel().getColumn(1).setResizable(false);
            tblInfo.getColumnModel().getColumn(2).setResizable(false);
            tblInfo.getColumnModel().getColumn(3).setResizable(false);
            tblInfo.getColumnModel().getColumn(4).setResizable(false);
            tblInfo.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanelTable);
        jPanelTable.setBounds(434, 147, 722, 405);

        lblEverestComputers.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblEverestComputers.setForeground(new java.awt.Color(255, 255, 255));
        lblEverestComputers.setText("EVEREST COMPUTERS Pvt. Ltd.");
        getContentPane().add(lblEverestComputers);
        lblEverestComputers.setBounds(170, 10, 880, 70);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/everest_1.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(10, 10, 125, 125);

        lblTime.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTime);
        lblTime.setBounds(970, 120, 180, 20);

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Everestcomputers69@hotmail.com");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(450, 70, 310, 40);

        lblAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Itahari-2, Sangit Chowk");
        getContentPane().add(lblAddress);
        lblAddress.setBounds(500, 100, 210, 30);

        lblDate.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(251, 251, 251));
        getContentPane().add(lblDate);
        lblDate.setBounds(970, 100, 180, 20);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/background.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-50, -10, 1380, 1220);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));

        mFile.setText("File");

        miOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/icons8_folder_30px.png"))); // NOI18N
        miOpen.setText("Open");
        miOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenActionPerformed(evt);
            }
        });
        mFile.add(miOpen);

        miSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/icons8_save_30px.png"))); // NOI18N
        miSave.setText("Save");
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        mFile.add(miSave);

        miImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        miImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/icons8_import_30px.png"))); // NOI18N
        miImport.setText("Import");
        miImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportActionPerformed(evt);
            }
        });
        mFile.add(miImport);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/icons8_exit_24px.png"))); // NOI18N
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        jMenuBar1.add(mFile);

        mHelp.setText("Help");

        miFAQs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        miFAQs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/icons8_faq_26px.png"))); // NOI18N
        miFAQs.setText("FAQs");
        miFAQs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFAQsActionPerformed(evt);
            }
        });
        mHelp.add(miFAQs);

        jMenuBar1.add(mHelp);

        mAbout.setText("About");

        miAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/coursework/icons8_about_24px.png"))); // NOI18N
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        mAbout.add(miAbout);

        jMenuBar1.add(mAbout);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1172, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenActionPerformed
        try {
            File file = new File("D:\\data.csv"); //sets file location
            
            if(file.exists()) {
                if(Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(file); //Opens the previously saved file
                }
                else {
                    JOptionPane.showMessageDialog(rootPane,"Not Supported in Desktop" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane,"File Doesn't Exists." ,"Error!!",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception ex) {
            Logger.getLogger(AppliancesInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miOpenActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane,"Do You Want To Close?","Warning!!",JOptionPane.YES_NO_OPTION); //Asks user to exit the program
        if(result == 0) {
            System.exit(0);
        }
        else {
            return;
        }
    }//GEN-LAST:event_miExitActionPerformed

    private void txtSearchByPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchByPriceFocusGained
        if(txtSearchByPrice.getText().equals("Enter Price To Search")) {
            txtSearchByPrice.setText(""); 
            txtSearchByPrice.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSearchByPriceFocusGained

    private void txtSearchByPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchByPriceFocusLost
        if(txtSearchByPrice.getText().equals("")) {
            txtSearchByPrice.setText("Enter Price To Search");
            txtSearchByPrice.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtSearchByPriceFocusLost
   
    private void btnSearchByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByPriceActionPerformed
        try {
            
            mergeSort(Item); //calls mergeSort() andd pass the array list as parameter
            int price = Integer.parseInt(txtSearchByPrice.getText().trim()); //converts string to integer type
            int i = binarySearch(Item,0,Item.size()-1,price); 
            
            if (i == -1) {
                JOptionPane.showMessageDialog(rootPane,"There is No Data with that Price." ,"No Any Data!!",JOptionPane.INFORMATION_MESSAGE);
            }
            
            else { //displaying searched details
                JOptionPane.showMessageDialog(rootPane,"\n"+" Model Number: "+Item.get(i).getModelNumber()+"\n Name: "+Item.get(i).getName()+"\n Price: "+Item.get(i).getPrice(),"Appliance Information",JOptionPane.INFORMATION_MESSAGE);
            }
        }   
        catch(NumberFormatException nfe) { //exception handling
            if (txtSearchByPrice.getText().equals("Enter Price To Search")) {
                JOptionPane.showMessageDialog(rootPane,"No Any Value is Inserted." ,"Empty Text Fields!!",JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane,"Please Enter Correct Data Type" ,"Error Data Type!!",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSearchByPriceActionPerformed

    private void btnSearchByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByCategoryActionPerformed
        String categorySearch = "";
        String cKey = (String)cbSearchByCategory.getSelectedItem(); //selecting key value from comboBox
        
        for(EverestComputers c:Item) {
            if(c.getCategory().equals(cKey)) {
                categorySearch +=  " Model Number:"+c.getModelNumber()+"\n Name:"+c.getName()+"\n Price:"+c.getPrice()+"\n Catagory:"+c.getCategory()+"\n\n"; //printing searched values
            }
        }
        
        if(!categorySearch.equals("")) {
            JOptionPane.showMessageDialog(rootPane," The Item is:"+"\n" + categorySearch);
        }
        else {
            JOptionPane.showMessageDialog(rootPane,"No Values in this Category" ,"No Such Data",JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnSearchByCategoryActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane,"Do You Want To Clear All The Text Fields?","Warning!!",JOptionPane.YES_NO_OPTION); //asks user to clear form
        if(result == 0) {
            txtModelNumber.setText("Enter Model Number");
            txtModelNumber.setForeground(new Color(153,153,153));
            txtName.setText("Enter Name");
            txtName.setForeground(new Color(153,153,153));
            cbCategory.setSelectedIndex(0);
            rbtnLow.setSelected(true);
            txtPrice.setText("Enter Price");
            txtPrice.setForeground(new Color(153,153,153));
            cbDiscount.setSelectedIndex(0);
            txtSearchByPrice.setText("Enter Price To Search");
            txtSearchByPrice.setForeground(new Color(153,153,153));
        }
        else {
            return;
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String modelNumber = txtModelNumber.getText().trim();
            String name = txtName.getText().trim();
            String category = (String)cbCategory.getSelectedItem();
            String recommendationType;
            
            //selecting recommendation from radio button
            if(rbtnLow.isSelected() == true){
                recommendationType = "Low"; 
            }
            else if(rbtnMedium.isSelected() == true){
                recommendationType = "Medium";
            }
            else {
                recommendationType = "High";
            }
            String recommendation = recommendationType;
            
            int price = Integer.parseInt(txtPrice.getText().trim());
            String discount = (String)cbDiscount.getSelectedItem();
            boolean emptyRowFlag = false;
            
            if (!modelNumber.equals("Enter Model Number") && !name.equals("Enter Name") && !recommendation.equals("Enter Recommendation") && !discount.equals("Enter Discount") && price > 0) {
                String[] value = {modelNumber, name, category, recommendation, Integer.toString(price), discount};
                int rowCount = tblInfo.getRowCount();
                int nextRow = 0;
                String p;
                
                do {
                    p = (String) tblInfo.getValueAt(nextRow, 0);
                    if (p != null && p.length() != 0) {
                        nextRow++;
                    } 
                    
                    else {
                        emptyRowFlag = true;
                    }
                } 
                while (nextRow < rowCount && !emptyRowFlag);
                
                if (Item.size() >= 1) {
                    
                    for (EverestComputers n : Item) {
                        
                        if (modelNumber.equals(n.getModelNumber())) {
                            emptyRowFlag = false;
                            JOptionPane.showMessageDialog(rootPane, "Model Number Must Not Be Same!!", "Error!!", JOptionPane.ERROR_MESSAGE);
                            return  ;
                        } 
                        
                        else {
                            emptyRowFlag = true;
                        }
                    }
                }
                else{
                    emptyRowFlag = true;
                }
                
                if (emptyRowFlag) {
                    int colCount = tblInfo.getColumnCount();
                    
                    if (nextRow < rowCount) {
                        
                        EverestComputers Object = new EverestComputers(modelNumber, name, category, recommendation, price, discount);
                        Item.add(Object);
                        mergeSort(Item);
                        
                        for (int i = 0; i < colCount; i++) {
                            tblInfo.setValueAt(value[i], nextRow, i);
                        }
                    } 
                    else {
                        JOptionPane.showMessageDialog(rootPane, "No Empty Row Found!!", "Error!!", JOptionPane.ERROR_MESSAGE);
                    }
                    save(); //calls save() method for saving the data to created file
                } 
            }
            else if(price < 1){
                JOptionPane.showMessageDialog(rootPane,"Input Value Not Valid For Price." ,"Invalid Input!!", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Do Not Leave The Textfields Empty", "Error!!", JOptionPane.ERROR_MESSAGE);
            }
        } 
        catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(rootPane, "No Data, Check Your Input", "Error!!", JOptionPane.ERROR_MESSAGE);
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Error While Retrieving Data, Check Your Input", "Error!!", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnAddActionPerformed
    
    private void save() {
        File file = new File("D:\\data.csv");//Loading of file
        
        try (FileWriter wr = new FileWriter(file)) {
            
            if (file.isFile()) {
                file.createNewFile();
            }    
            
            for (EverestComputers s : Item) {
                String v[] = {s.getModelNumber(), s.getName(), s.getCategory(), s.getRecommendation(), Integer.toString(s.getPrice()), s.getDiscount()};
                
                for (int i = 0; i < v.length; i++) {
                    wr.append(v[i]);
                    if (i == v.length - 1) {
                        break;
                    }
                    wr.append(",");//CSV comma separated value
                }
                wr.append("\n");
            }
            wr.flush();
        }
        catch (IOException ex) {
            Logger.getLogger(AppliancesInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void txtModelNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelNumberFocusLost
        if(txtModelNumber.getText().equals("")) {
            txtModelNumber.setText("Enter Model Number");
            txtModelNumber.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtModelNumberFocusLost

    private void txtModelNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelNumberFocusGained
        if(txtModelNumber.getText().equals("Enter Model Number")) {
            txtModelNumber.setText("");
            txtModelNumber.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtModelNumberFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        if(txtPrice.getText().equals("")) {
            txtPrice.setText("Enter Price");
            txtPrice.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        if(txtPrice.getText().equals("Enter Price")) {
            txtPrice.setText("");
            txtPrice.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if(txtName.getText().equals("")) {
            txtName.setText("Enter Name");
            txtName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        if(txtName.getText().equals("Enter Name")) {
            txtName.setText("");
            txtName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        dboxAbout.show();
        dboxAbout.setLocationRelativeTo(null);
    }//GEN-LAST:event_miAboutActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtSearchByPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchByPriceKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSearchByPriceKeyTyped

    private void miFAQsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFAQsActionPerformed
       // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\Users\\Sulav\\OneDrive\\Documents\\NetBeansProjects\\Program\\src\\my\\coursework\\manual.pdf");
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Sorry, There is no FAQs", " Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miFAQsActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dboxAbout.hide();
    }//GEN-LAST:event_btnOkActionPerformed

    private void miImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportActionPerformed
        try {
            File selectedFile = new File("D:\\data.csv");
            if(selectedFile.exists()) {
                if(selectedFile.length()==0) {
                    JOptionPane.showMessageDialog(rootPane,"There is No Previously Saved Data" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                }
                else{
                    BufferedReader br = new BufferedReader(new FileReader(selectedFile));
                    Object[] lines = br.lines().toArray();
                    int rowCount = tblInfo.getRowCount();
                    int nextRow = 0;
                    boolean emptyRowFlag = false;
                    String p;

                    for (int i = 0; i < lines.length; i++) {  
                        String[] row = lines[i].toString().split(",");
                        do {
                            p = (String) tblInfo.getValueAt(nextRow, 0);
                    
                            if (p != null && p.length() != 0) {
                                nextRow++;
                            } 
                    
                            else {
                                emptyRowFlag = true;
                            }
                        }
                        while (nextRow < rowCount && !emptyRowFlag);

                        if (emptyRowFlag) {
                            int colCount = tblInfo.getColumnCount();
                    
                            if (nextRow < rowCount) {

                                for (int j = 0; j < colCount; j++) {
                                    tblInfo.setValueAt(row[j], nextRow, j);
                                }
                            }
                        } 
                        else {
                            JOptionPane.showMessageDialog(rootPane, "No Empty Row Found!!", "Error!!", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } 
            else{
                selectedFile.createNewFile();
                JOptionPane.showMessageDialog(rootPane,"There is No Previously Saved Data" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                return;
            }
        }
        
        catch (Exception ex) {
            Logger.getLogger(AppliancesInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miImportActionPerformed

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        if(Item.size()>=1) {
            save();
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "No Any Data Inserted in Table!!", "Error!!", JOptionPane.ERROR_MESSAGE);      
        }
    }//GEN-LAST:event_miSaveActionPerformed
    
    public void mergeSort(ArrayList<EverestComputers> price) {
        if (price.size() <= 1) {
            return;
        }
        
        int firstLength = price.size() / 2;
        int secondLength = price.size() - firstLength;
        ArrayList<EverestComputers> first = new ArrayList();
        ArrayList<EverestComputers> second = new ArrayList();
        
        for (int i = 0; i < firstLength; i++) {
            first.add(price.get(i));
        }

        for (int i = 0; i < secondLength; i++) {
            second.add(price.get(firstLength + i));
        }
        
        mergeSort(first);
        mergeSort(second);
        merge(first, second, price);
    }

    public static void merge(ArrayList<EverestComputers> first, ArrayList<EverestComputers> second, ArrayList<EverestComputers> price) {
        int iFirst = 0;
        int iSecond = 0;
        int j = 0;
        
        while (iFirst < first.size() && iSecond < second.size()) {
            if (first.get(iFirst).getPrice() < second.get(iSecond).getPrice()) {
                price.set(j, first.get(iFirst));
                iFirst++;
            }
            else {
                price.set(j, second.get(iSecond));
                iSecond++;
            }
            j++;
        }
        
        while (iFirst < first.size()) {
            price.set(j, first.get(iFirst));
            iFirst++;
            j++;
        }

        while (iSecond < second.size()) {
            price.set(j, second.get(iSecond));
            iSecond++;
            j++;
        }
    }
    
    public static int binarySearch(ArrayList<EverestComputers> priceSearch, int low, int high, int key) {  
        int mid = (low + high)/2;  
        if (low <= high){ 
            
            if ( priceSearch.get(mid).getPrice() == key ){  
                return mid;     
            }
            
            else if ( priceSearch.get(mid).getPrice() > key ){  
                return binarySearch(priceSearch, low, mid-1, key);
            }
            
            else{  
                return binarySearch(priceSearch, mid+1, high, key); 
            }  
        }  
        
        else { 
            return -1;
        }  
    }  
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppliancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppliancesInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup btnGrpRecommendation;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSearchByCategory;
    private javax.swing.JButton btnSearchByPrice;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JComboBox<String> cbDiscount;
    private javax.swing.JComboBox<String> cbSearchByCategory;
    private javax.swing.JDialog dboxAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelSearchByItem;
    private javax.swing.JPanel jPanelSearchByPrice;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneAddSearch;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEverestComputers;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoAbout;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu mAbout;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miFAQs;
    private javax.swing.JMenuItem miImport;
    private javax.swing.JMenuItem miOpen;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JRadioButton rbtnHigh;
    private javax.swing.JRadioButton rbtnLow;
    private javax.swing.JRadioButton rbtnMedium;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextArea txtAbout;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearchByPrice;
    // End of variables declaration//GEN-END:variables
}
